//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CardModel
{
	public CardSuit Suit;
	public CardValue Value;

	public CardModel (CardSuit suit, CardValue value)
	{
		Suit = suit;
		Value = value;
	}
}


