//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

public class DeckView : MonoBehaviour
{
	public GameObject CardPrefab;

	DeckController deckController;

	GameObject deckPile;
	GameObject discardPile;
	GameObject trumpCardPile;

	public void Initialize()
	{
		deckPile = gameObject.transform.Find ("deckPile").gameObject;
		discardPile = gameObject.transform.Find ("discardPile").gameObject;
		trumpCardPile = gameObject.transform.Find ("trumpCardPile").gameObject;
		deckController = GetComponent<DeckController> ();
		StartCoroutine (Deal ());
	}

	IEnumerator Deal()
	{
		yield return null;
		GameCard trumpCard = GameObjectUtils.AddAndPosition (CardPrefab, trumpCardPile, Vector3.zero).GetComponent<GameCard> ();
		trumpCard.GetComponent<GameCard> ().Initialize (deckController.TakeCardFromDeck ());
	}

	public GameCard DrawCard()
	{
		CardModel cm = deckController.TakeCardFromDeck();
		GameCard dealtCard = GameObjectUtils.AddAndPosition(CardPrefab, deckPile, Vector3.zero).GetComponent<GameCard>();
		dealtCard.Initialize(cm);
		return dealtCard;
	}

}


