//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class SimpleButton : MonoBehaviour
{
	public delegate void ClickHandler(SimpleButton btn);

	public ClickHandler OnClick;

	void Update()
	{
		//if(null == OnClick)return;
		if(Input.GetMouseButtonDown(0))
		{
			RaycastHit hit;
			Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);
			if(Physics.Raycast(ray, out hit))
			{
				GameObject go = hit.transform.gameObject;
				if(go.Equals(this.gameObject))
				{
					Debug.Log("Clicked! Name: " + gameObject.name);
					if(null != OnClick)
						OnClick(this);
				}
			}
		}
	}
}


